<a href="https://colab.research.google.com/github/HemaKavuri/DATA-690-FALL-STATISTICAL-ANAYLSIS-VISUALIZATION/blob/main/Assignment_06/Assignment06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment 06
### Note:
- For visualization, you should use Plotly Express 
- Use this notebook as your template and follow the instructions

The first half of this assignment is similar to assignment 04.

This gives you a chance to refresh.

The second half is new and gives you a chance to perform additional practices.

You also get a chance to use some of the Python libraries and techniques.

The links to the zip file is:

- https://collegescorecard.ed.gov/data (This web page contains the link to the zip file)

- https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip (The link to the zip file)

You can run `!wget` command in Colab notebook to retrieve it directly, then run `!unzip` command to extract files (I have provided the cells to do so next for your convenience)

Your folder structure should look like this in your Colab enviroment:

- ...
- 'MERGED1996_97_PP.csv',
- 'MERGED2015_16_PP.csv',
- ...
- 'MERGED2017_18_PP.csv'
- ...

**Note: you should refresh the folder to see all files.**

## Step 1 - Retrieve the zip file

In [1]:
!wget https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip

--2022-10-10 01:22:45--  https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip
Resolving ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)... 3.30.49.38, 3.30.138.208, 2600:1f12:18a:7d01:ad67:f64c:95d6:78ed, ...
Connecting to ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)|3.30.49.38|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 410294884 (391M) [application/zip]
Saving to: ‘CollegeScorecard_Raw_Data_09012022.zip.3’

CollegeScorecard_Ra   8%[>                   ]  33.23M  18.6MB/s    in 1.8s

2022-10-10 01:22:48 (18.6 MB/s) - Connection closed at byte 34848340. Retrying.

--2022-10-10 01:22:49--  (try: 2)  https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data_09012022.zip
Connecting to ed-public-download.app.cloud.gov (ed-public-download.app.cloud.gov)|3.30.49.38|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 410294884 (391M), 375446544 (358M) remaining [application/zip]
Saving to: ‘CollegeScorecard_Raw_Data_09012022.zip.3’

CollegeScorecard_Ra 100%[+==================>] 391.29M  32.9MB/s    in 14s

2022-10-10 01:23:04 (24.9 MB/s) - ‘CollegeScorecard_Raw_Data_09012022.zip.3’ saved [410294884/410294884]

## Step 2 - Unzip the zip file

In [2]:
!unzip CollegeScorecard_Raw_Data_09012022.zip

Archive:  CollegeScorecard_Raw_Data_09012022.zip
replace Crosswalks.zip? [y]es, [n]o, [A]ll, [N]one, [r]ename:

## Step 3 - Import Libraries

In [3]:
import os 
import pandas as pd
import plotly.express as px

## Step 4 - Display the current working directory using os.getcwd()

You would need to import a standard Python library called os which stands for operating system. so place that import statement in the previous cell. Since your notebook and your data files may or may not in the same folder, you want to make sure what the current working folder is and how to access a data file in a different folder.

In [4]:
cwd = os.getcwd() 
print("Current working directory is ",cwd)

Current working directory is  /content

## Step 5 - Get the list of file names

os library has a method call listdir which generates a list of files in a directory/folder. Use this method to assign the contents (list of file names) of the data folder to a variable and display it. If necessary, you can use ../ construct to traverse to the parent folder and then to another foloder parallel to the current folder

In [5]:
files_list = []
for path in os.listdir(cwd):
    if os.path.isfile(os.path.join(cwd, path)):
        files_list.append(path)
print(files_list)

['MERGED2006_07_PP.csv', 'MERGED2009_10_PP.csv', 'MERGED2003_04_PP.csv', 'MERGED1998_99_PP.csv', 'Crosswalks.zip', 'MERGED2012_13_PP.csv', 'MERGED2019_20_PP.csv', 'MERGED2011_12_PP.csv', 'MERGED2014_15_PP.csv', 'Most-Recent-Cohorts-Field-of-Study.csv', 'MERGED2000_01_PP.csv', 'MERGED2007_08_PP.csv', 'MERGED2016_17_PP.csv', 'FieldOfStudyData1718_1819_PP.csv', 'MERGED2018_19_PP.csv', 'MERGED2008_09_PP.csv', 'CollegeScorecard_Raw_Data_09012022.zip.3', 'MERGED2002_03_PP.csv', 'MERGED2004_05_PP.csv', 'MERGED2010_11_PP.csv', 'MERGED2013_14_PP.csv', 'MERGED2005_06_PP.csv', 'CollegeScorecard_Raw_Data_09012022.zip.1', 'FieldOfStudyData1516_1617_PP.csv', 'MERGED1999_00_PP.csv', 'MERGED2015_16_PP.csv', 'MERGED1996_97_PP.csv', 'FieldOfStudyData1415_1516_PP.csv', 'CollegeScorecard_Raw_Data_09012022.zip.2', 'FieldOfStudyData1617_1718_PP.csv', 'MERGED2017_18_PP.csv', 'data.yaml', 'Most-Recent-Cohorts-Institution.csv', 'MERGED1997_98_PP.csv', 'MERGED2020_21_PP.csv', 'CollegeScorecard_Raw_Data_09012022.zip', 'MERGED2001_02_PP.csv']

## Step 6 - Process only the yearly data files

The folder contains files that are not the yearly data files. Write code to remove the unwanted files from the list variable.

Note: don't remove/delete these files from the folder in the folder.
For example, use the file extension to only use the csv files or use the name patter - data file name begins with "MERGED". You can use the concept of list comprehension to write just *one* line of code as well as using a for loop, your choice.

In [6]:
files_csv = []
for file in os.listdir(cwd):
    if file.startswith('MERGED'):
        files_csv.append(file)
print(files_csv)

['MERGED2006_07_PP.csv', 'MERGED2009_10_PP.csv', 'MERGED2003_04_PP.csv', 'MERGED1998_99_PP.csv', 'MERGED2012_13_PP.csv', 'MERGED2019_20_PP.csv', 'MERGED2011_12_PP.csv', 'MERGED2014_15_PP.csv', 'MERGED2000_01_PP.csv', 'MERGED2007_08_PP.csv', 'MERGED2016_17_PP.csv', 'MERGED2018_19_PP.csv', 'MERGED2008_09_PP.csv', 'MERGED2002_03_PP.csv', 'MERGED2004_05_PP.csv', 'MERGED2010_11_PP.csv', 'MERGED2013_14_PP.csv', 'MERGED2005_06_PP.csv', 'MERGED1999_00_PP.csv', 'MERGED2015_16_PP.csv', 'MERGED1996_97_PP.csv', 'MERGED2017_18_PP.csv', 'MERGED1997_98_PP.csv', 'MERGED2020_21_PP.csv', 'MERGED2001_02_PP.csv']

## Step 7 - Load data files
 
Now that you have a clean list of the yearly files, you want to loop through them and read them into a dataframe one at a time. You only load six columns: ["UNITID", "INSTNM", "STABBR", "REGION", "ADM_RATE", "TUITIONFEE_IN"].

You should use "usecols" option of Pandas to avoid reading unwanted columns. You also want to add a new column call "YEAR" to differentiate the data frames from each other. The YEAR variable should be yyyy format so tht you can convert them into integer. If you use the format yyyy-yy (such as 1997-98 school year), you will not be able to convert them directly to integer. If you use scatter plot, the YEAR needs to be converted to integer or float. 

You would use an empty list and append the yearly dataframes to the list. After all data files are loaded and appended to the list, you would use Pandas to concatenate them into a new single data frame.

Note: this exercise incorporates many techques we learned before:

- list (creating an empty, append an item to the list)
- for loop 
- read only the needed columns from a file (using usecols option)
- add a new column to a data frame
- concatenate multiple dataframes into a single one

This exercise may appear challenging but it worths the effort. You will learn a lot and love it. I promise.

In [7]:
files_csv.sort()
universities=pd.read_csv("/content/"+ files_csv[0], usecols = ['UNITID','INSTNM','STABBR','REGION','ADM_RATE','TUITIONFEE_IN'])
universities['YEAR']= files_csv[0][6:10]

for file in files_csv[1:]:
  df=pd.read_csv("/content/"+ file, usecols = ['UNITID','INSTNM','STABBR','REGION','ADM_RATE','TUITIONFEE_IN'])
  df['YEAR']= file[6:10]
  universities=universities.append(df,ignore_index=True)

universities.head()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
0,100636,Community College of the Air Force,AL,0.0,NaN,NaN,1996
1,100654,Alabama A & M University,AL,5.0,NaN,NaN,1996
2,100663,University of Alabama at Birmingham,AL,5.0,NaN,NaN,1996
3,100672,ALABAMA AVIATION AND TECHNICAL COLLEGE,AL,5.0,NaN,NaN,1996
4,100690,Amridge University,AL,5.0,NaN,NaN,1996

## Step 8 - Explore the new dataframe 

For example, # of observations, varibles, head, tail, sample, missing values, statistics, etc.

**No of Observations**

In [8]:
print("no of rows = ",universities.shape[0])
print("no of columns =",universities.shape[1])

no of rows =  176707
no of columns = 7

**Varibles**

In [9]:
for col in universities.columns:
    print(col)

UNITID
INSTNM
STABBR
REGION
ADM_RATE
TUITIONFEE_IN
YEAR

**Head**

In [10]:
universities.head()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
0,100636,Community College of the Air Force,AL,0.0,NaN,NaN,1996
1,100654,Alabama A & M University,AL,5.0,NaN,NaN,1996
2,100663,University of Alabama at Birmingham,AL,5.0,NaN,NaN,1996
3,100672,ALABAMA AVIATION AND TECHNICAL COLLEGE,AL,5.0,NaN,NaN,1996
4,100690,Amridge University,AL,5.0,NaN,NaN,1996

**Tail**

In [11]:
universities.tail()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
176702,49576719,Pennsylvania State University-Penn State Wilke...,PA,2.0,NaN,13604.0,2020
176703,49576720,Pennsylvania State University-Penn State York,PA,2.0,NaN,14486.0,2020
176704,49576721,Pennsylvania State University-Penn State Great...,PA,2.0,NaN,NaN,2020
176705,49576722,Pennsylvania State University-Penn State Harri...,PA,2.0,NaN,15216.0,2020
176706,49576723,Pennsylvania State University-Penn State Brand...,PA,2.0,NaN,14486.0,2020

**Sample**

In [12]:
universities.sample(5)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
151942,198914,Mayland Community College,NC,5.0,NaN,2558.0,2017
175108,459064,Empire Beauty School-Pineville,NC,5.0,NaN,NaN,2020
154683,449384,Gnomon,CA,8.0,0.5333,31380.0,2017
71851,230825,Burlington College,VT,1.0,0.8571,15600.0,2006
110191,457794,EDP School,NY,2.0,NaN,4250.0,2011

**Missing Values**

In [13]:
universities.isnull().sum()

UNITID                0
INSTNM                0
STABBR                0
REGION                1
ADM_RATE         127844
TUITIONFEE_IN     89840
YEAR                  0
dtype: int64

**Statistics**

In [14]:
universities.describe()

             UNITID         REGION      ADM_RATE  TUITIONFEE_IN
count  1.767070e+05  176706.000000  48863.000000   86867.000000
mean   1.054338e+06       4.559279      0.693785   12037.588290
std    4.959072e+06       2.188341      0.217019   10462.970227
min    1.006360e+05       0.000000      0.000000       0.000000
25%    1.641730e+05       3.000000      0.556700    3936.000000
50%    2.136310e+05       5.000000      0.719500    9422.000000
75%    4.137780e+05       6.000000      0.857100   16490.000000
max    4.957672e+07       9.000000      1.000000   74787.000000

## Step 9 - UMBC 

The dataframe contains many years of data of all U.S. colleges. let's just look at UMBC. Filter/query the dataframe to retrieve only rows that belong to UMBC (one row represent one year). Save the UMNC data to a new data frame. using a new variable for the UMBC data frame, so that the old big data frame is still available for later use.

In [15]:
college1=universities.loc[universities['INSTNM']=='University of Maryland-Baltimore County']
college1.head()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000

## Step 10 - Explore the new dataframe

For example, # of observations, varibles, head, tail, sample, missing values, statistics, etc

**No of Obeseravtions**

In [16]:
print("no of rows = ",college1.shape[0])
print("no of columns =",college1.shape[1])

no of rows =  25
no of columns = 7

**Varibles**

In [17]:
for col in college1.columns:
    print(col)

UNITID
INSTNM
STABBR
REGION
ADM_RATE
TUITIONFEE_IN
YEAR

**Head**

In [18]:
college1.head()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000

**Tail**

In [19]:
college1.tail()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
143685,163268,University of Maryland-Baltimore County,MD,2.0,0.5683,11264.0,2016
150891,163268,University of Maryland-Baltimore County,MD,2.0,0.6021,11518.0,2017
157940,163268,University of Maryland-Baltimore County,MD,2.0,0.5794,11778.0,2018
164723,163268,University of Maryland-Baltimore County,MD,2.0,0.6103,12028.0,2019
171401,163268,University of Maryland-Baltimore County,MD,2.0,0.6948,9420.0,2020

**sample**

In [20]:
college1.sample(5)

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
97506,163268,University of Maryland-Baltimore County,MD,2.0,0.6589,9171.0,2010
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996
69401,163268,University of Maryland-Baltimore County,MD,2.0,0.7153,8622.0,2006
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005

**Missing Values**

In [21]:
college1.isnull().sum()

UNITID           0
INSTNM           0
STABBR           0
REGION           0
ADM_RATE         5
TUITIONFEE_IN    4
YEAR             0
dtype: int64

**Statistics**

In [22]:
college1.describe()

         UNITID  REGION   ADM_RATE  TUITIONFEE_IN
count      25.0    25.0  20.000000      21.000000
mean   163268.0     2.0   0.641880    9168.571429
std         0.0     0.0   0.051853    1854.082079
min    163268.0     2.0   0.568300    5490.000000
25%    163268.0     2.0   0.600600    8520.000000
50%    163268.0     2.0   0.632100    9171.000000
75%    163268.0     2.0   0.690825   10384.000000
max    163268.0     2.0   0.717400   12028.000000

## Step 11 - Plot UMBC's in-state tution overtime Bar Chart

In [23]:
fig=px.bar(college1,x='YEAR',y='TUITIONFEE_IN')
fig.show()

## Step 12 - Plot UMBC's in-state tution overtime using line Chart

In [24]:
fig=px.line(college1,x='YEAR',y='TUITIONFEE_IN',width=750,height=500)
fig.show()

## Step 13 - Tuition Growth Rate

Now let's look at the tuition growth rate year over year. We need to calculate UMBC tuition change percentage each year. First convert the TUITIONFEE_IN column to a Python List

In [25]:
growth_rate=[]
Tutionfee=college1["TUITIONFEE_IN"].values.tolist()
for i in range(len(Tutionfee)):
  growth_rate.append((Tutionfee[i]-Tutionfee[i-1]) / Tutionfee[i-1])
growth_rate

[nan,
 nan,
 nan,
 nan,
 nan,
 0.07650273224043716,
 0.07648054145516074,
 0.16127004086765168,
 0.08554412560909583,
 0.06234413965087282,
 0.011971830985915493,
 0.009974483878450475,
 0.008268259072117593,
 0.010478359908883827,
 0.03370153291253381,
 0.03227565151019518,
 0.03137213478398648,
 0.031134780827529702,
 0.03138657131505761,
 0.05989984591679507,
 0.02344175904052335,
 0.022549715909090908,
 0.022573363431151242,
 0.021226014603498048,
 -0.2168274027269704]

## Step 14 - Loop through the list and calculate the % change each year over the prior year

This takes some effort. Not hard, just some abstract/logical thinking and some experiments. Have fun on this one.

In [26]:
Percentage_change=[]
for i in range(0, len(growth_rate)):
  Percentage_change.append(growth_rate[i] / growth_rate[i-1])
Percentage_change

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.9997099347353153,
 2.108641463557127,
 0.5304402798489939,
 0.7287951008554564,
 0.19202816901408448,
 0.8331627710235102,
 0.8289410432534638,
 1.2672994178688939,
 3.2162984670874657,
 0.9576909036737514,
 0.972006243594392,
 0.9924342427414938,
 1.0080871128954687,
 1.908454584462952,
 0.39134923774404257,
 0.9619464081219168,
 1.0010486838129433,
 0.9403124469349635,
 -10.21517259727303]

## Step 15 - Round up the percentage to two decimal points

The resulting number has many decimal points which are unnecessary and not visually appealing. You can use for loop. Or better, use list comprehension for simplicity/brevity.

In [27]:
for i in range(0, len(Percentage_change)):
  Percentage_change[i]=round(Percentage_change[i],2)
  print(Percentage_change[i])

nan
nan
nan
nan
nan
nan
1.0
2.11
0.53
0.73
0.19
0.83
0.83
1.27
3.22
0.96
0.97
0.99
1.01
1.91
0.39
0.96
1.0
0.94
-10.22

## Step 16 - Add the list of the percentages to the dataframe as a new column ("PCT_CHANGE")

Not as hard as you may think. If you get stuck, you think too hard. Google it and you will find the answer.

In [28]:
college1['PCT_CHANGE']=Percentage_change
college1.head(10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR,PCT_CHANGE
2151,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1996,NaN
9056,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1997,NaN
15923,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1998,NaN
22598,163268,University of Maryland-Baltimore County,MD,2.0,NaN,NaN,1999,NaN
29178,163268,University of Maryland-Baltimore County,MD,2.0,NaN,5490.0,2000,NaN
35821,163268,University of Maryland-Baltimore County,MD,2.0,0.6551,5910.0,2001,NaN
42524,163268,University of Maryland-Baltimore County,MD,2.0,0.6327,6362.0,2002,1.00
49156,163268,University of Maryland-Baltimore County,MD,2.0,0.5757,7388.0,2003,2.11
55786,163268,University of Maryland-Baltimore County,MD,2.0,0.7014,8020.0,2004,0.53
62522,163268,University of Maryland-Baltimore County,MD,2.0,0.7143,8520.0,2005,0.73

## Step 17 - Finaly, we can make the plot tuition growth rate year over year - bar first, then line chart

In [29]:
fig=px.bar(college1,x='YEAR',y='PCT_CHANGE',width=750,height=500)
fig.show()

In [30]:
fig=px.line(college1,x='YEAR',y='PCT_CHANGE',width=750,height=500)
fig.show()

## Step 18 - Define Growth Rate Function

Since we want to do the same calculation for JHU. Instead of doing it piecemeal as we did for UMBC. Let's create a function which can be reused for any college. This function takes a list of tuitions and return a list of percentage changes year over year. This function can be used later.

In [31]:
def GrowthRate(tutions):
  growth_rate=[]
  Percentage_change=[]
  for i in range(len(tutions)):
    growth_rate.append((tutions[i]-tutions[i-1]) / tutions[i-1])
  for i in range(0, len(growth_rate)):
    Percentage_change.append(round((growth_rate[i] / growth_rate[i-1]),2))
  return Percentage_change

## Step 19 - Get JHU Data

The dataframe contains many years of data of all U.S. colleges. Let's just look at JHU. Filter/query the dataframe to retrieve only rows that belong to JHU. Save the JHU data to a new data frame using a new variable so that the old big data frame is still available for later use.

In [32]:
college2= universities.loc[universities['INSTNM']=='Johns Hopkins University']
college2.head()

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR
2139,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1996
9046,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1997
15914,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1998
22589,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1999
29169,162928,Johns Hopkins University,MD,2.0,NaN,24930.0,2000

## Step 20 - Plot JHU's in-state tuition overtime

Let's plot bar and then line chart.

In [33]:
fig=px.bar(college2,x='YEAR',y='TUITIONFEE_IN',width=750,height=500)
fig.show()

In [34]:
fig=px.line(college2,x='YEAR',y='TUITIONFEE_IN',width=750,height=500)
fig.show()

## Step 21 - Calculate Tuition Growth Rate using the Function defined earlier

In [35]:
Tutionfee=college2["TUITIONFEE_IN"].values.tolist()
GrowthRate(Tutionfee)

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.88,
 1.09,
 1.0,
 1.0,
 1.47,
 0.82,
 0.85,
 0.77,
 1.02,
 1.01,
 0.67,
 1.83,
 0.73,
 1.0,
 1.0,
 1.0,
 0.86,
 1.0,
 -0.72]

## Step 22 - Add the list of percentage changes to the dataframe as a new column ("PCT_CHANGE")

In [36]:
college2['PCT_CHANGE']=GrowthRate(Tutionfee)
college2.head(10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,UNITID,INSTNM,STABBR,REGION,ADM_RATE,TUITIONFEE_IN,YEAR,PCT_CHANGE
2139,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1996,NaN
9046,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1997,NaN
15914,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1998,NaN
22589,162928,Johns Hopkins University,MD,2.0,NaN,NaN,1999,NaN
29169,162928,Johns Hopkins University,MD,2.0,NaN,24930.0,2000,NaN
35812,162928,Johns Hopkins University,MD,2.0,0.3431,26210.0,2001,NaN
42515,162928,Johns Hopkins University,MD,2.0,0.3506,27390.0,2002,0.88
49148,162928,Johns Hopkins University,MD,2.0,0.3060,28730.0,2003,1.09
55779,162928,Johns Hopkins University,MD,2.0,0.3071,30140.0,2004,1.00
62515,162928,Johns Hopkins University,MD,2.0,0.3509,31620.0,2005,1.00

## Step 23 - Plot the JHU percentage changes tuitions over time

Bar plot first, then line plot.

In [37]:
fig=px.bar(college2,x='YEAR',y='PCT_CHANGE',width=750,height=500)
fig.show()

In [38]:
fig=px.line(college2,x='YEAR',y='PCT_CHANGE',width=750,height=500)
fig.show()

## Step 24 - Compare UMBC and JHU 

In order to plot both UMBC and JHU tuition change over time in the same plot, we need to combine the two datasets using the common key of YEAR. 

First make a umbc2 dataframe with only two columns needed. We don't need other columns. Also change the column name from "PCT_CHANGE" to "UMBC_PCT" in preparation for the merge. This is because both umbc and jhu dataframe have the same column name "PCT_CHANGE", we rename them to there is no collision during the merge. BTW, Pandas handles collision gracefully, Feel free to try it without changing the column names.

In [39]:
umbc=pd.DataFrame()
umbc['YEAR']=college1['YEAR']
umbc['UMBC_PCT']=college1['PCT_CHANGE']
umbc.head(10)

       YEAR  UMBC_PCT
2151   1996       NaN
9056   1997       NaN
15923  1998       NaN
22598  1999       NaN
29178  2000       NaN
35821  2001       NaN
42524  2002      1.00
49156  2003      2.11
55786  2004      0.53
62522  2005      0.73

## Step 25 

Then make a jhu2 dataframe with only two columns needed. WE don't need other columns. Also change the column name from "PCT_CHANGE" to "JHU_PCT"  in preparation for the merge

In [40]:
jhu=pd.DataFrame()
jhu['YEAR']=college2['YEAR']
jhu['JHU_PCT']=college2['PCT_CHANGE']
jhu.head(10)

       YEAR  JHU_PCT
2139   1996      NaN
9046   1997      NaN
15914  1998      NaN
22589  1999      NaN
29169  2000      NaN
35812  2001      NaN
42515  2002     0.88
49148  2003     1.09
55779  2004     1.00
62515  2005     1.00

## Step 26 - Merger the two data frames and display the new dataframe

In [44]:
UMBC_JHU=umbc.merge(jhu, on='YEAR')
UMBC_JHU.tail(10)

    YEAR  UMBC_PCT  JHU_PCT
15  2011      0.96     1.01
16  2012      0.97     0.67
17  2013      0.99     1.83
18  2014      1.01     0.73
19  2015      1.91     1.00
20  2016      0.39     1.00
21  2017      0.96     1.00
22  2018      1.00     0.86
23  2019      0.94     1.00
24  2020    -10.22    -0.72

## Step 27 - Plot UMBC and JHU separately on the same line plot

In [43]:
fig=px.line(UMBC_JHU, x='YEAR', y= ['UMBC_PCT','JHU_PCT'],width=750,height=500)
fig.show()

## Step 28 - Document your observation of the comparison plots using the following Markdown cell

From the above plot we can say that their is a drastic change in UMBC tutuion fee, it falls from 1 percentage to -10 percentage. Percentage change of JHU Tution Fee is not much fluctuating when compare to UMBC Tution fee. This observation is seen in year 2020. Both Univeristies having same Tution fee in year between 2007-2008 and 2017-2018.